class CONSCONSTANTS:
    SP_UPDATE_CAMPO = 'SP_UPDATE_CAMPO'
    SP_SELECT_ALL = 'SP_SELECT_ALL'
    SP_UPDATE_GRUPOS = 'SP_UPDATE_GRUPOS'
    SP_UPDATE_SEGMENTACIONES = 'SP_UPDATE_SEGMENTACIONES'
    SP_INSERT_ALLIN = 'SP_INSERT_ALLIN'
    SP_COUNTER = 'SP_COUNTER'